on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    name: Build, Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '~1.17.7'
      - name: Build
        run: go build
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.2
      - name: Run tests
        run: go test -v

